# Generated by Django 4.0.1 on 2022-01-31 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('vehicleType', models.CharField(choices=[('ECO', 'Economy'), ('ECO XL', 'Economy XL'), ('LUX', 'Luxury')], default='ECO', max_length=20)),
                ('licenseNumber', models.CharField(max_length=20)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rideID', models.BigIntegerField(default=0)),
                ('passengerNumber', models.PositiveIntegerField(default=0)),
                ('ownership', models.CharField(choices=[('OWNER', 'Owner'), ('SHARER', 'Sharer')], default='OWNER', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RideInfo',
            fields=[
                ('rideID', models.BigAutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=50)),
                ('arriveTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('passengerNumber', models.PositiveIntegerField(default=0)),
                ('vehicleType', models.CharField(choices=[('ECO', 'Economy'), ('ECO XL', 'Economy XL'), ('LUX', 'Luxury')], default='ECO', max_length=20)),
                ('shareable', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=20)),
                ('rideStatus', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='OPEN', max_length=20)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.driver')),
            ],
        ),
    ]
